### ISSUE TITLE
API Authenication Failed, correct keys for this device?

### ISSUE THREAD

**Issue by klipsoh** [PhilWilliams-dev/absolutePowershell#3]
Hello,

Every time I try to run device freeze, I am unable to because I receive API authentication Failed error. The weird thing is, I am able to run the function Set-AbsoluteAuth to authenticate and I'm able to run Get-Device with my authentication and it returns the device. When I try to post, my authentication fails.

Do you know what could be causing this issue?

Thank you!

**Comment by SciFi-Bob** [comment]
Hi!,

So firstly I no longer work for Absolute and as such do not have any access to an account to test against, so to some extent this is abandoware.

That said, from what I recall it was very important that all of the parameters were formatted correctly.  If you want to post the full command that you are running (Change the obvious bits to something similar but anonymous) I'll have a look for you.  I know that the function works.. well assuming that they have not changed the API in the last 2 years.

**Comment by klipsoh** [comment]
Thank you so much for your quick response! I took your advice and looked over at my parameters and sure enough I was missing one. I was able to successfully freeze a device. Thank you again!
